ChargeBee Automation Configuration:
  Site: 'test'
  ClientName: 'thedinnerdaily'

  Customers_Validation: False
  Subscriptions_Validation: True
  Invoices_Validation: False

  IsRecurly: False
  IsRecurlyDS1vsDS2: False
  IsMollie: False
  IsMollieDS1vsDS2: False
  type:
     - DS2vsDS1
#    - DS2vsDS3
  dateFormet:
    - "%Y-%m-%d %H:%M:%S"
  #    - "%Y-%m-%d %H:%M"
  #    - "%Y-%m-%d"

  # ------------------   CUSTOMER INFORMATION   ------------------
  # Mapping Source Columns vs : Destination Columns

  Customers_SourceFile:
    #Moille validation requires "Customers" & "FinalPayments" files
    #Recurly validation requires "CustomerAddressOfAccount" & "CustomerAddressOfBilling" files
    "/Users/cb-muneendra/dataValidation/data_validation_qa/ds1Tods2/thedinnerdailyDS2_Cus.xlsx"
  Customers_DestinationFile:
    "/Users/cb-muneendra/dataValidation/data_validation_qa/ds1Tods2/thedinnerdailyDS1_Cus.xlsx"

  Customers_KeyColumns:
    - "customer[id] : id"

  Customers_Columns:
    - "customer[id] : id"
    - "customer[created_at] : created"
    - "customer[name] : name"
    - "customer[email] : email"
    - "customer[preferred_currency_code] : currency"
    - "customer[meta_data] : metadata"
    - "billing_address[line1] : address.line1"
    - "billing_address[state] : address.state"
    - "billing_address[zip] : address.postal_code"
    - "billing_address[country] : address.country"



  # ------------------   SUBSCRIPTIONS INFORMATION   ------------------
  # Mapping Source Columns vs : Destination Columns

  Subscriptions_SourceFile:
    #Moille validation requires "Subscriptions" & "Transactions" files
    #Recurly validation requires "Addon_Columns" & "Coupon_Columns" files
    "/Users/cb-muneendra/dataValidation/data_validation_qa/ds1Tods2/thedinnerdaily_DS2_Subs.xlsx"

  Subscriptions_DestinationFile:
    "/Users/cb-muneendra/dataValidation/data_validation_qa/ds1Tods2/thedinnerdaily_DS1_Subs.xlsx"

  Subscriptions_KeyColumns:
    - "subscription[id] : id"

  Subscriptions_Columns:
    - "customer[id] : customer"
    - "subscription[id] : id"
    - "subscription[created_at] : created"
    - "subscription_items[item_price_id][0] : items.data[0].price.id"
    - "subscription_items[quantity][0] : items.data[0].quantity"
    - "subscription_items[unit_price][0] : items.data[0].price.unit_amount"
    - "subscription[status] : status"
    - "subscription[trial_start] : trial_start"
    - "subscription[trial_end] : trial_end"
    - "subscription[started_at] : start_date"
    - "subscription[current_term_start] : current_period_start"
    - "subscription[current_term_end] : current_period_end"
    - "subscription[auto_collection] : collection_method"
    - "coupon_ids[0] : discount.coupon.id"
    - "subscription[meta_data] : metadata"


  # ------------------   INVOICES INFORMATION   ------------------
  # Mapping Source Columns vs : Destination Columns

  Invoices_SourceFile:
    #Moille validation requires "invoice-lines", "Subscriptions" & "Transactions" files and need to configure scheduled for date
    #Recurly validation requires "Invoice_Adjustment_Columns" & "Payment_Merge_Columns" files
    "/Users/cb-muneendra/Downloads/the dinner daily - QA - DS2 Invoice.csv"

  Invoices_DestinationFile:
    "/Users/cb-muneendra/Git/cb_data_validation/readAPI/ds3files/thedinnerdaily_DS3_AllInvoices.xlsx"

  Invoices_KeyColumns:
    - "invoice[id] : invoice_id"

  Invoices_Columns:
    - "invoice[id] : invoice_id"
    - "invoice[currency_code] : invoice_currency_code"
    - "invoice[customer_id] : invoice_customer_id"
    - "invoice[date] : invoice_date"
    - "invoice[price_type] : invoice_price_type"
    - "invoice[status] : invoice_status"
#    - "invoice[stripe_id] : invoice_stripe_id"
    - "invoice[subscription_id] : invoice_subscription_id"
    - "invoice[total] : invoice_total"
    - "line_items[amount][0] : line_items_amount[0]"
    - "line_items[date_from][0] : line_items_date_from[0]"
    - "line_items[date_to][0] : line_items_date_to[0]"
    - "line_items[description][0] : line_items_description[0]"
    - "line_items[entity_id][0] : line_items_entity_id[0]"
    - "line_items[entity_type][0] : line_items_entity_type[0]"
    - "line_items[id][0] : line_items_id[0]"
    - "line_items[quantity][0] : line_items_quantity[0]"
    - "shipping_address[first_name] : invoice_shipping_address_first_name"
    - "shipping_address[last_name] : invoice_shipping_address_last_name"
    - "payments[amount][0] : payments_txn_amount[0]"
    - "payments[date][0] : payments_txn_date[0]"
    - "discounts[amount][0] : discounts_discount_amount[0]_x"
    - "discounts[entity_id][0] : discounts_entity_id[0]_x"
    - "discounts[entity_type][0] : discounts_discount_type[0]_x"
    - "discounts[line_item_id][0] : discounts_line_item_id[0]_x"
    - "payments[amount][1] : payments_txn_amount[1]"
    - "payments[date][1] : payments_txn_date[1]"

  Date_Columns:
    - "subscription[created_at] : created"
    - "subscription[current_term_start] : current_period_start"
    - "subscription[current_term_end] : current_period_end"
    - "subscription[trial_start] : trial_start"
    - "subscription[trial_end] : trial_end"
    - "subscription[started_at] : start_date"
    - "line_items[date_from][0] : line_items_date_from[0]"
    - "line_items[date_to][0] : line_items_date_to[0]"
    - "subscription[start_date] : subscription_start_date"
    - "invoice[date] : invoice[date]"
    - "line_items[date_from][0] : line_items[date_from][0]"
    - "line_items[date_to][0] : line_items[date_to][0]"
    - "payments[date][0] : payments[date][0]"
    - "line_items[date_from][1] : line_items[date_from][1]"
    - "line_items[date_to][1] : line_items[date_to][1]"
    - "line_items[date_from][2] : line_items[date_from][2]"
    - "line_items[date_to][2] : line_items[date_to][2]"
    - "line_items[date_from][3] : line_items[date_from][3]"
    - "line_items[date_from][4] : line_items[date_from][4]"
    - "line_items[date_to][3] : line_items[date_to][3]"
    - "line_items[date_to][4] : line_items[date_to][4]"
    - "line_items[date_from] : Date_From"
    - "line_items[date_to] : Date_To"
    - "customer[created_at] : customer_created_at"
    - "invoice[date] : invoice_date"
    - "payments[date][0] : payments_txn_date[0]"
    - "line_items[date_from][0] : line_item_date_from[0]"
    - "line_items[date_to][0] : line_item_date_to[0]"
    - "line_items[date_from][1] : line_item_date_from[1]"
    - "line_items[date_to][1] : line_item_date_to[1]"
    - "line_items[date_from][2] : line_item_date_from[2]"
    - "line_items[date_to][2] : line_item_date_to[2]"
    - "line_items[date_from][3] : line_item_date_from[3]"
    - "line_items[date_to][3] : line_item_date_to[3]"
    - "line_items[date_from][4] : line_item_date_from[4]"
    - "line_items[date_to][4] : line_item_date_to[4]"
    - "line_items[date_from][5] : line_item_date_from[5]"
    - "line_items[date_to][5] : line_item_date_to[5]"
    - "line_items[date_from][6] : line_item_date_from[6]"
    - "line_items[date_to][6] : line_item_date_to[6]"
    - "line_items[date_from][7] : line_item_date_from[7]"
    - "line_items[date_to][7] : line_item_date_to[7]"
    - "line_items[date_from][8] : line_item_date_from[8]"
    - "line_items[date_to][8] : line_item_date_to[8]"
    - "line_items[date_from][9] : line_item_date_from[9]"
    - "line_items[date_to][9] : line_item_date_to[9]"
    - "subscription[created_at] : subscription_created_at"
    - "subscription[started_at] : subscription_started_at"
    - "subscription[current_term_start] : subscription_current_term_start"
    - "subscription[current_term_end] : subscription_current_term_end"
    - "invoice[date] : invoice_date"
    - "invoice[due_date] : invoice_due_date"
    - "line_items[date_from][0] : line_item_date_from[0]"
    - "line_items[date_to][0] : line_item_date_to[0]"
    - "line_items[date_from][1] : line_item_date_from[1]"
    - "line_items[date_to][1] : line_item_date_to[1]"
    - "line_items[date_from][2] : line_item_date_from[2]"
    - "line_items[date_to][2] : line_item_date_to[2]"
    - "line_items[date_from][3] : line_item_date_from[3]"
    - "line_items[date_to][3] : line_item_date_to[3]"
    - "payments[date][0] : payments_txn_date[0]"
    - "subscription[created_at] : subscription_created_at"
    - "subscription[started_at] : subscription_started_at"
    - "invoice[due_date] : invoice_due_date"
    - "subscription[created_at] : subscription_created_at"
    - "subscription[trial_start] : subscription_trial_start"
    - "subscription[trial_end] : subscription_trial_end"
    - "subscription[started_at] : subscription_started_at"
    - "subscription[current_term_start] : subscription_current_term_start"
    - "subscription[current_term_end] : subscription_current_term_end"
    - "subscription[cancelled_at] : subscription_cancelled_at"
    - "subscription[start_date] : subscription_started_at"
    - "subscription[current_term_start] : subscription_current_term_start"
    - "subscription[current_term_end] : subscription_current_term_end"
    - "subscription[pause_date] : subscription_pause_date"
    - "invoice[date] : Invoice_Date"
    - "payments[date][0] : Paid_On"
    - "subscription[created_at] : subscriptions.created_at"
    - "subscription[started_at] : subscriptions.started_at"
    - "subscription[current_term_start] : subscriptions.current_term_start"
    - "subscription[current_term_end] : subscriptions.current_term_end"
    - "subscription[cancelled_at] : subscriptions.cancelled_at"
    - "customer[created_at] : Created_At"
    - "invoice[date] : date"
    - "line_items[date_from][0] : line_items[date_from][0]"
    - "line_items[date_to][0] : line_items[date_to][0]"
    - "payments[date][0] : payments_0_date"
    - "subscription[created_at] : subscription_created_at"
    - "customer[created_at] : customer_created_at"
    - "subscription[started_at] : subscription_started_at"
    - "subscription[current_term_start] : subscription_current_term_start"
    - "subscription[current_term_end] : subscription_current_term_end"
    - "subscription[cancelled_at] : subscription_cancelled_at"
    - "customer[created_at] : customer_created_at"
    - 'created : invoice[date]'
    - 'lines.data[0].period.start : line_items[date_from][0]'
    - 'lines.data[0].period.end : line_items[date_to][0]'
    - 'lines.data[1].period.start : line_items[date_from][1]'
    - 'lines.data[1].period.end : line_items[date_to][1]'
    - 'lines.data[2].period.start : line_items[date_from][2]'
    - 'lines.data[2].period.end : line_items[date_to][2]'
    - 'lines.data[3].period.start : line_items[date_from][3]'
    - 'lines.data[3].period.end : line_items[date_to][3]'

  Int_Columns:
    - "customer[phone] : customer_phone"
    - "billing_address[phone] : customer_billing_address_phone"
    - "payments[amount][0] : payments_txn_amount[0]"
    - "line_items[unit_amount][0] : line_item_unit_amount[0]"
    - "line_items[quantity][1] : line_item_quantity[1]"
    - "line_items[amount][1] : line_item_amount[1]"
    - "line_items[quantity][2] : line_item_quantity[2]"
    - "line_items[amount][2] : line_item_amount[2]"
    - "line_items[quantity][3] : line_item_quantity[3]"
    - "line_items[amount][3] : line_item_amount[3]"
    - "line_items[quantity][4] : line_item_quantity[4]"
    - "line_items[amount][4] : line_item_amount[4]"
    - "line_items[quantity][5] : line_item_quantity[5]"
    - "line_items[amount][5] : line_item_amount[5]"
    - "line_items[quantity][6] : line_item_quantity[6]"
    - "line_items[amount][6] : line_item_amount[6]"
    - "line_items[quantity][7] : line_item_quantity[7]"
    - "line_items[amount][7] : line_item_amount[7]"
    - "line_items[quantity][8] : line_item_quantity[8]"
    - "line_items[amount][8] : line_item_amount[8]"
    - "line_items[quantity][9] : line_item_quantity[9]"
    - "line_items[amount][9] : line_item_amount[9]"
    - "subscription_items[quantity][1] : item_quantity[1]"
    - "subscription_items[unit_price][1] : item_unit_price[1]"
    - "subscription_items[quantity][2] : item_quantity[2]"
    - "subscription_items[unit_price][2] : item_unit_price[2]"
    - "subscription_items[quantity][3] : item_quantity[3]"
    - "subscription_items[unit_price][3] : item_unit_price[3]"
    - "subscription_items[quantity][4] : item_quantity[4]"
    - "subscription_items[unit_price][4] : item_unit_price[4]"
    - "subscription_items[quantity][5] : item_quantity[5]"
    - "subscription_items[unit_price][5] : item_unit_price[5]"
    - "subscription_items[quantity][6] : item_quantity[6]"
    - "subscription_items[unit_price][6] : item_unit_price[6]"
    - "subscription_items[quantity][7] : item_quantity[7]"
    - "subscription_items[unit_price][7] : item_unit_price[7]"
    - "subscription_items[quantity][8] : item_quantity[8]"
    - "subscription_items[unit_price][8] : item_unit_price[8]"
    - "subscription_items[quantity][9] : item_quantity[9]"
    - "subscription_items[unit_price][9] : item_unit_price[9]"
    - "subscription_items[quantity][0] : item_quantity[0]"
    - "subscription_items[unit_price][0] : item_unit_price[0]"
    - "subscription_items[quantity][1] : item_quantity[1]"
    - "subscription_items[unit_price][1] : item_unit_price[1]"
    - "subscription_items[quantity][2] : item_quantity[2]"
    - "subscription_items[unit_price][2] : item_unit_price[2]"
    - "subscription_items[quantity][3] : item_quantity[3]"
    - "subscription_items[unit_price][3] : item_unit_price[3]"
    - "shipping_address[zip] : subscription_shipping_address_zip"
    - "subscription[po_number] : subscription_po_number"
    - "invoice[total] : invoice_total"
    - "line_items[quantity][0] : line_item_quantity[0]"
    - "line_items[unit_amount][0] : line_item_unit_amount[0]"
    - "line_items[tax1_amount][0] : line_item_taxes_tax_amount[0]"
    - "line_items[quantity][1] : line_item_quantity[1]"
    - "line_items[unit_amount][1] : line_item_unit_amount[1]"
    - "line_items[tax1_amount][1] : line_item_taxes_tax_amount[1]"
    - "line_items[quantity][2] : line_item_quantity[2]"
    - "line_items[unit_amount][2] : line_item_unit_amount[2]"
    - "line_items[tax1_amount][2] : line_item_taxes_tax_name[2]"
    - "line_items[quantity][3] : line_item_quantity[3]"
    - "line_items[unit_amount][3] : line_item_unit_amount[3]"
    - "line_items[tax1_amount][3] : line_item_tax1_amount[3]"
    - "payments[amount][0] : payments_txn_amount[0]"
    - "subscription_items[quantity][0] : item_quantity[0]"
    - "subscription_items[quantity][1] : item_quantity[1]"
    - "subscription_items[quantity][2] : item_quantity[2]"
    - "subscription_items[quantity][3] : item_quantity[3]"
    - "subscription_items[quantity][4] : item_quantity[4]"
    - "subscription_items[quantity][5] : item_quantity[5]"

  Float_Columns:
    - "subscription_items[unit_price][0] : item_unit_price[0]"
    - "subscription_items[unit_price][1] : item_unit_price[1]"
    - "subscription_items[unit_price][2] : item_unit_price[2]"
    - "subscription_items[unit_price][3] : item_unit_price[3]"
    - "subscription_items[unit_price][4] : item_unit_price[4]"
    - "subscription_items[unit_price][5] : item_unit_price[5]"

  Email_Columns:
    - "customer[email] : Email"
    - "customer[email] : customer_email"
    - "billing_address[email] : customer_billing_address_email"

  Zip_Columns:
    - "billing_address[zip] : customer_billing_address_zip"
    - "billing_address[zip] : Billing_Address_Zip"
    - "shipping_address[zip] : subscription_shipping_address_zip"
    - "billing_address[zip] : customer_billing_address_zip"
    - 'customer_shipping.address.postal_code : shipping_address[state_code]'
    - 'address.postal_code : billing_address[zip]'






