ChargeBee Automation Configuration:
  Site: 'test'
  ClientName: 'Numerade'

  Customers_Validation: False
  Subscriptions_Validation: True
  Invoices_Validation: False

  IsRecurly: False
  IsRecurlyDS1vsDS2: False
  IsMollie: False
  IsMollieDS1vsDS2: False
  type:
    #    - DS1vsDS2
    - DS2vsDS3
  dateFormet:
#    - "%Y-%m-%d %H:%M:%S"
      - "%Y-%m-%d %H:%M"
#      - "%Y-%m-%d"

  # ------------------   CUSTOMER INFORMATION   ------------------
  # Mapping Source Columns vs : Destination Columns

  Customers_SourceFile:
    "/Users/cb-muneendra/Desktop/Numerad_B2_DS2_Customer.xlsx"
  Customers_DestinationFile:
    "/Users/cb-muneendra/Git/cb_data_validation/readAPI/ds3files/numerade_DS3_AllCustomers.xlsx"

  Customers_KeyColumns:
    - "customer[id] : customer_id"

  Customers_Columns:
    - "customer[id] : customer_id"
    - "customer[created_at] : customer_created_at"
    - "customer[first_name] : customer_first_name"
    - "customer[last_name] : customer_last_name"
    - "customer[email] : customer_email"
    - "customer[preferred_currency_code] : customer_preferred_currency_code"
    - "customer[meta_data] : customer_meta_data"
    - "billing_address[first_name] : customer_billing_address_first_name"
    - "billing_address[last_name] : customer_billing_address_last_name"
    - "billing_address[line1] : customer_billing_address_line1"
    - "billing_address[state] : customer_billing_address_state"
    - "billing_address[zip] : customer_billing_address_zip"
    - "billing_address[country] : customer_billing_address_country"



  # ------------------   SUBSCRIPTIONS INFORMATION   ------------------
  # Mapping Source Columns vs : Destination Columns

  Subscriptions_SourceFile:
    "/Users/cb-muneendra/Desktop/numerade_I2_B1_DS2_subscriptions.xlsx"

  Subscriptions_DestinationFile:
    "/Users/cb-muneendra/Git/cb_data_validation/readAPI/ds3files/numerade_DS3_AllSubscriptions.xlsx"

  Subscriptions_KeyColumns:
    - "subscription[id] : subscription_id"

  Subscriptions_Columns:
    - "subscription[id] : subscription_id"
    - "customer[id] : customer_id"
    - "subscription[created_at] : subscription_created_at"
    - "subscription_items[item_price_id][0] : item_item_price_id[0]"
    - "subscription_items[quantity][0] : item_quantity[0]"
    - "subscription_items[unit_price][0] : item_unit_price[0]"
    - "subscription[status] : subscription_status"
    - "subscription[started_at] : subscription_started_at"
    - "subscription[current_term_start] : subscription_current_term_start"
    - "subscription[current_term_end] : subscription_current_term_end"
    - "subscription[cancelled_at] : subscription_cancelled_at"
    - "subscription[auto_collection] : subscription_auto_collection"
    - "coupon_ids[0] : subscription_coupon"
    - "subscription[meta_data] : subscription_meta_data"



  # ------------------   INVOICES INFORMATION   ------------------
  # Mapping Source Columns vs : Destination Columns

  Invoices_SourceFile:
    "/Users/cb-muneendra/Desktop/Numerad_DS2_invoice.xlsx"

  Invoices_DestinationFile:
    "/Users/cb-muneendra/Git/cb_data_validation/readAPI/ds3files/numerade_DS3_AllInvoices.xlsx"

  Invoices_KeyColumns:
    - "invoice[id] : invoice_id"

  Invoices_Columns:
    - "invoice[id] : invoice_id"
    - "invoice[currency_code] : invoice_currency_code"
    - "invoice[customer_id] : invoice_customer_id"
    - "invoice[date] : invoice_date"
    - "invoice[status] : invoice_status"
    - "invoice[subscription_id] : invoice_subscription_id"
    - "invoice[total] : invoice_total"
    - "line_items[amount][0] : line_items_amount[0]"
    - "line_items[date_from][0] : line_items_date_from[0]"
    - "line_items[date_to][0] : line_items_date_to[0]"
    - "line_items[description][0] : line_items_description[0]"
    - "line_items[entity_id][0] : line_items_entity_id[0]"
    - "line_items[entity_type][0] : line_items_entity_type[0]"
    - "line_items[id][0] : line_items_id[0]"
    - "line_items[quantity][0] : line_items_quantity[0]"
    - "payments[amount][0] : payments_txn_amount[0]"
    - "payments[date][0] : payments_txn_date[0]"
    - "discounts[amount][0] : discounts_discount_amount[0]"
    - "discounts[entity_id][0]org : discounts_entity_id[0]"
    - "discounts[entity_type][0] : discounts_discount_type[0]"

  Date_Columns:
    - "line_items[date_from][0] : line_items_date_from[0]"
    - "line_items[date_to][0] : line_items_date_to[0]"
    - "subscription[start_date] : subscription_start_date"
    - "invoice[date] : invoice[date]"
    - "line_items[date_from][0] : line_items[date_from][0]"
    - "line_items[date_to][0] : line_items[date_to][0]"
    - "payments[date][0] : payments[date][0]"
    - "line_items[date_from][1] : line_items[date_from][1]"
    - "line_items[date_to][1] : line_items[date_to][1]"
    - "line_items[date_from][2] : line_items[date_from][2]"
    - "line_items[date_to][2] : line_items[date_to][2]"
    - "line_items[date_from][3] : line_items[date_from][3]"
    - "line_items[date_from][4] : line_items[date_from][4]"
    - "line_items[date_to][3] : line_items[date_to][3]"
    - "line_items[date_to][4] : line_items[date_to][4]"
    - "line_items[date_from] : Date_From"
    - "line_items[date_to] : Date_To"
    - "customer[created_at] : customer_created_at"
    - "invoice[date] : invoice_date"
    - "payments[date][0] : payments_txn_date[0]"
    - "line_items[date_from][0] : line_item_date_from[0]"
    - "line_items[date_to][0] : line_item_date_to[0]"
    - "line_items[date_from][1] : line_item_date_from[1]"
    - "line_items[date_to][1] : line_item_date_to[1]"
    - "line_items[date_from][2] : line_item_date_from[2]"
    - "line_items[date_to][2] : line_item_date_to[2]"
    - "line_items[date_from][3] : line_item_date_from[3]"
    - "line_items[date_to][3] : line_item_date_to[3]"
    - "line_items[date_from][4] : line_item_date_from[4]"
    - "line_items[date_to][4] : line_item_date_to[4]"
    - "line_items[date_from][5] : line_item_date_from[5]"
    - "line_items[date_to][5] : line_item_date_to[5]"
    - "line_items[date_from][6] : line_item_date_from[6]"
    - "line_items[date_to][6] : line_item_date_to[6]"
    - "line_items[date_from][7] : line_item_date_from[7]"
    - "line_items[date_to][7] : line_item_date_to[7]"
    - "line_items[date_from][8] : line_item_date_from[8]"
    - "line_items[date_to][8] : line_item_date_to[8]"
    - "line_items[date_from][9] : line_item_date_from[9]"
    - "line_items[date_to][9] : line_item_date_to[9]"
    - "subscription[created_at] : subscription_created_at"
    - "subscription[started_at] : subscription_started_at"
    - "subscription[current_term_start] : subscription_current_term_start"
    - "subscription[current_term_end] : subscription_current_term_end"
    - "invoice[date] : invoice_date"
    - "invoice[due_date] : invoice_due_date"
    - "line_items[date_from][0] : line_item_date_from[0]"
    - "line_items[date_to][0] : line_item_date_to[0]"
    - "line_items[date_from][1] : line_item_date_from[1]"
    - "line_items[date_to][1] : line_item_date_to[1]"
    - "line_items[date_from][2] : line_item_date_from[2]"
    - "line_items[date_to][2] : line_item_date_to[2]"
    - "line_items[date_from][3] : line_item_date_from[3]"
    - "line_items[date_to][3] : line_item_date_to[3]"
    - "payments[date][0] : payments_txn_date[0]"
    - "subscription[created_at] : subscription_created_at"
    - "subscription[started_at] : subscription_started_at"
    - "invoice[due_date] : invoice_due_date"
    - "subscription[created_at] : subscription_created_at"
    - "subscription[trial_start] : subscription_trial_start"
    - "subscription[trial_end] : subscription_trial_end"
    - "subscription[started_at] : subscription_started_at"
    - "subscription[current_term_start] : subscription_current_term_start"
    - "subscription[current_term_end] : subscription_current_term_end"
    - "subscription[cancelled_at] : subscription_cancelled_at"
    - "subscription[start_date] : subscription_started_at"
    - "subscription[current_term_start] : subscription_current_term_start"
    - "subscription[current_term_end] : subscription_current_term_end"
    - "subscription[pause_date] : subscription_pause_date"
    - "invoice[date] : Invoice_Date"
    - "payments[date][0] : Paid_On"
    - "subscription[created_at] : subscriptions.created_at"
    - "subscription[started_at] : subscriptions.started_at"
    - "subscription[current_term_start] : subscriptions.current_term_start"
    - "subscription[current_term_end] : subscriptions.current_term_end"
    - "subscription[cancelled_at] : subscriptions.cancelled_at"
    - "customer[created_at] : Created_At"
    - "invoice[date] : date"
    - "line_items[date_from][0] : line_items[date_from][0]"
    - "line_items[date_to][0] : line_items[date_to][0]"
    - "payments[date][0] : payments_0_date"
    - "subscription[created_at] : subscription_created_at"
    - "customer[created_at] : customer_created_at"
    - "subscription[started_at] : subscription_started_at"
    - "subscription[current_term_start] : subscription_current_term_start"
    - "subscription[current_term_end] : subscription_current_term_end"
    - "subscription[cancelled_at] : subscription_cancelled_at"
    - "customer[created_at] : customer_created_at"
    - 'created : invoice[date]'
    - 'lines.data[0].period.start : line_items[date_from][0]'
    - 'lines.data[0].period.end : line_items[date_to][0]'
    - 'lines.data[1].period.start : line_items[date_from][1]'
    - 'lines.data[1].period.end : line_items[date_to][1]'
    - 'lines.data[2].period.start : line_items[date_from][2]'
    - 'lines.data[2].period.end : line_items[date_to][2]'
    - 'lines.data[3].period.start : line_items[date_from][3]'
    - 'lines.data[3].period.end : line_items[date_to][3]'

  Int_Columns:
    - "customer[phone] : customer_phone"
    - "billing_address[phone] : customer_billing_address_phone"
    - "payments[amount][0] : payments_txn_amount[0]"
    - "line_items[unit_amount][0] : line_item_unit_amount[0]"
    - "line_items[quantity][1] : line_item_quantity[1]"
    - "line_items[amount][1] : line_item_amount[1]"
    - "line_items[quantity][2] : line_item_quantity[2]"
    - "line_items[amount][2] : line_item_amount[2]"
    - "line_items[quantity][3] : line_item_quantity[3]"
    - "line_items[amount][3] : line_item_amount[3]"
    - "line_items[quantity][4] : line_item_quantity[4]"
    - "line_items[amount][4] : line_item_amount[4]"
    - "line_items[quantity][5] : line_item_quantity[5]"
    - "line_items[amount][5] : line_item_amount[5]"
    - "line_items[quantity][6] : line_item_quantity[6]"
    - "line_items[amount][6] : line_item_amount[6]"
    - "line_items[quantity][7] : line_item_quantity[7]"
    - "line_items[amount][7] : line_item_amount[7]"
    - "line_items[quantity][8] : line_item_quantity[8]"
    - "line_items[amount][8] : line_item_amount[8]"
    - "line_items[quantity][9] : line_item_quantity[9]"
    - "line_items[amount][9] : line_item_amount[9]"
    - "subscription_items[quantity][1] : item_quantity[1]"
    - "subscription_items[unit_price][1] : item_unit_price[1]"
    - "subscription_items[quantity][2] : item_quantity[2]"
    - "subscription_items[unit_price][2] : item_unit_price[2]"
    - "subscription_items[quantity][3] : item_quantity[3]"
    - "subscription_items[unit_price][3] : item_unit_price[3]"
    - "subscription_items[quantity][4] : item_quantity[4]"
    - "subscription_items[unit_price][4] : item_unit_price[4]"
    - "subscription_items[quantity][5] : item_quantity[5]"
    - "subscription_items[unit_price][5] : item_unit_price[5]"
    - "subscription_items[quantity][6] : item_quantity[6]"
    - "subscription_items[unit_price][6] : item_unit_price[6]"
    - "subscription_items[quantity][7] : item_quantity[7]"
    - "subscription_items[unit_price][7] : item_unit_price[7]"
    - "subscription_items[quantity][8] : item_quantity[8]"
    - "subscription_items[unit_price][8] : item_unit_price[8]"
    - "subscription_items[quantity][9] : item_quantity[9]"
    - "subscription_items[unit_price][9] : item_unit_price[9]"
    - "subscription_items[quantity][0] : item_quantity[0]"
    - "subscription_items[unit_price][0] : item_unit_price[0]"
    - "subscription_items[quantity][1] : item_quantity[1]"
    - "subscription_items[unit_price][1] : item_unit_price[1]"
    - "subscription_items[quantity][2] : item_quantity[2]"
    - "subscription_items[unit_price][2] : item_unit_price[2]"
    - "subscription_items[quantity][3] : item_quantity[3]"
    - "subscription_items[unit_price][3] : item_unit_price[3]"
    - "shipping_address[zip] : subscription_shipping_address_zip"
    - "subscription[po_number] : subscription_po_number"
    - "invoice[total] : invoice_total"
    - "line_items[quantity][0] : line_item_quantity[0]"
    - "line_items[unit_amount][0] : line_item_unit_amount[0]"
    - "line_items[tax1_amount][0] : line_item_taxes_tax_amount[0]"
    - "line_items[quantity][1] : line_item_quantity[1]"
    - "line_items[unit_amount][1] : line_item_unit_amount[1]"
    - "line_items[tax1_amount][1] : line_item_taxes_tax_amount[1]"
    - "line_items[quantity][2] : line_item_quantity[2]"
    - "line_items[unit_amount][2] : line_item_unit_amount[2]"
    - "line_items[tax1_amount][2] : line_item_taxes_tax_name[2]"
    - "line_items[quantity][3] : line_item_quantity[3]"
    - "line_items[unit_amount][3] : line_item_unit_amount[3]"
    - "line_items[tax1_amount][3] : line_item_tax1_amount[3]"
    - "payments[amount][0] : payments_txn_amount[0]"
    - "subscription_items[quantity][0] : item_quantity[0]"
    - "subscription_items[quantity][1] : item_quantity[1]"
    - "subscription_items[quantity][2] : item_quantity[2]"
    - "subscription_items[quantity][3] : item_quantity[3]"
    - "subscription_items[quantity][4] : item_quantity[4]"
    - "subscription_items[quantity][5] : item_quantity[5]"

  Float_Columns:
    - "subscription_items[unit_price][0] : item_unit_price[0]"
    - "subscription_items[unit_price][1] : item_unit_price[1]"
    - "subscription_items[unit_price][2] : item_unit_price[2]"
    - "subscription_items[unit_price][3] : item_unit_price[3]"
    - "subscription_items[unit_price][4] : item_unit_price[4]"
    - "subscription_items[unit_price][5] : item_unit_price[5]"

  Email_Columns:
    - "customer[email] : Email"
    - "customer[email] : customer_email"
    - "billing_address[email] : customer_billing_address_email"

  Zip_Columns:
    - "billing_address[zip] : customer_billing_address_zip"
    - "billing_address[zip] : Billing_Address_Zip"
    - "shipping_address[zip] : subscription_shipping_address_zip"
    - "billing_address[zip] : customer_billing_address_zip"
    - 'customer_shipping.address.postal_code : shipping_address[state_code]'
    - 'address.postal_code : billing_address[zip]'






