ChargeBee Automation Configuration:
  Site: 'Live'
  ClientName: 'dropix'

  Customers_Validation: False
  Subscriptions_Validation: True
  Invoices_Validation: True

  IsRecurly: False
  IsRecurlyDS1vsDS2: False
  IsMollie: False
  IsMollieDS1vsDS2: False
  type:
    #    - DS1vsDS2
    - DS2vsDS3
  dateFormet:
    - "%Y-%m-%d %H:%M:%S"
#    - "%Y-%m-%d %H"
#      - "%Y-%m-%d %H:%M"
#      - "%Y-%m-%d"

  # ------------------   CUSTOMER INFORMATION   ------------------
  # Mapping Source Columns vs : Destination Columns

  Customers_SourceFile:



    "/Users/cb-muneendra/Desktop/Dropix_Live_DS2_Customers.xlsx"
  Customers_DestinationFile:
    "/Users/cb-muneendra/Git/cb_data_validation/readAPI/ds3files/dropix_Live_AllCustomers.xlsx"

  Customers_KeyColumns:
    - "customer[id] : customer_id"

  Customers_Columns:
    - "customer[id] : customer_id"
    - "customer[created_at] : customer_created_at"
    - "customer[first_name] : customer_first_name"
    - "customer[last_name] : customer_last_name"
    - "customer[email] : customer_email"
    - "customer[phone] : customer_phone"
    - "customer[preferred_currency_code] : customer_preferred_currency_code"
    - "customer[locale] : customer_locale"
    - "customer[meta_data] : customer_meta_data"
    - "billing_address[first_name] : customer_billing_address_first_name"
    - "billing_address[last_name] : customer_billing_address_last_name"
    - "billing_address[line1] : customer_billing_address_line1"
    - "billing_address[line2] : customer_billing_address_line2"
    - "billing_address[city] : customer_billing_address_city"
    - "billing_address[zip] : customer_billing_address_zip"
    - "billing_address[country] : customer_billing_address_country"


  # ------------------   SUBSCRIPTIONS INFORMATION   ------------------
  # Mapping Source Columns vs : Destination Columns

  Subscriptions_SourceFile:
    "/Users/cb-muneendra/Desktop/Dropix_Live_DS2_Subscription.xlsx"

  Subscriptions_DestinationFile:
    "/Users/cb-muneendra/Git/cb_data_validation/readAPI/ds3files/dropix_Live_AllSubscriptions.xlsx"

  Subscriptions_KeyColumns:
    - "subscription[id] : subscription_id"

  Subscriptions_Columns:
    - "subscription[id] : subscription_id"
    - "customer[id] : customer_id"
    - "subscription[created_at] : subscription_created_at"
    - "subscription_items[item_price_id][0] : item_price_id[0]"
    - "subscription_items[quantity][0] : item_quantity[0]"
    - "subscription_items[unit_price][0] : item_unit_price[0]"
    - "subscription[status] : subscription_status"
    - "subscription[trial_start] : subscription_trial_start"
    - "subscription[trial_end] : subscription_trial_end"
    - "subscription[started_at] : subscription_started_at"
    - "subscription[current_term_start] : subscription_current_term_start"
    - "subscription[current_term_end] : subscription_current_term_end"
    - "subscription[cancelled_at] : subscription_cancelled_at"
    - "subscription[auto_collection] : subscription_auto_collection"
    - "subscription[meta_data] : subscription_meta_data"
    - "shipping_address[first_name] : subscription_shipping_address_first_name"
    - "shipping_address[last_name] : subscription_shipping_address_last_name"
    - "shipping_address[country] : subscription_shipping_address_country"

  # ------------------   INVOICES INFORMATION   ------------------
  # Mapping Source Columns vs : Destination Columns

  Invoices_SourceFile:
    "/Users/cb-muneendra/Desktop/Dropix_Live_DS2_Invoice.xlsx"

  Invoices_DestinationFile:
    "/Users/cb-muneendra/Git/cb_data_validation/readAPI/ds3files/dropix_Live_AllInvoices.xlsx"

  Invoices_KeyColumns:
    - "invoice[id] : invoice_id"

  Invoices_Columns:
    - "invoice[id] : invoice_id"
    - "billing_address[city] : invoice_billing_address_city"
    - "billing_address[country] : invoice_billing_address_country"
    - "billing_address[first_name] : invoice_billing_address_first_name"
    - "billing_address[last_name] : invoice_billing_address_last_name"
    - "billing_address[line1] : invoice_billing_address_line1"
    - "billing_address[line2] : invoice_billing_address_line2"
    - "billing_address[zip] : invoice_billing_address_zip"
    - "invoice[currency_code] : invoice_currency_code"
    - "invoice[customer_id] : invoice_customer_id"
    - "invoice[date] : invoice_date"
    - "invoice[price_type] : invoice_price_type"
    - "invoice[status] : invoice_status"
    - "invoice[subscription_id] : invoice_subscription_id"
    - "invoice[total] : invoice_total"
    - "line_items[amount][0] : line_items_amount[0]"
    - "line_items[date_from][0] : line_items_date_from[0]"
    - "line_items[date_to][0] : line_items_date_to[0]"
    - "line_items[description][0] : line_items_description[0]"
    - "line_items[entity_id][0] : line_items_entity_id[0]"
    - "line_items[entity_type][0] : line_items_entity_type[0]"
    - "line_items[id][0] : line_items_id[0]"
    - "line_items[quantity][0] : line_items_quantity[0]"
    - "line_items[tax1_amount][0] : line_items_taxes_tax_amount[0]"
    - "line_items[tax1_name][0] : line_items_taxes_tax_name[0]"
    - "payments[amount][0] : payments_txn_amount[0]"
    - "payments[date][0] : payments_txn_date[0]"
    - "shipping_address[city] : invoice_shipping_address_city"
    - "shipping_address[country] : invoice_shipping_address_country"
    - "shipping_address[first_name] : invoice_shipping_address_first_name"
    - "shipping_address[last_name] : invoice_shipping_address_last_name"
    - "shipping_address[line1] : invoice_shipping_address_line1"
    - "shipping_address[phone] : invoice_shipping_address_phone"
    - "shipping_address[zip] : invoice_shipping_address_zip"
    - "taxes[rate][0] : line_items_taxes_tax_rate[0]"
    - "line_items[amount][1] : line_items_amount[1]"
    - "line_items[date_from][1] : line_items_date_from[1]"
    - "line_items[date_to][1] : line_items_date_to[1]"
    - "line_items[description][1] : line_items_description[1]"
    - "line_items[entity_id][1] : line_items_entity_id[1]"
    - "line_items[entity_type][1] : line_items_entity_type[1]"
    - "line_items[id][1] : line_items_id[1]"
    - "line_items[quantity][1] : line_items_quantity[1]"
    - "line_items[tax1_amount][1] : line_items_taxes_tax_amount[1]"
    - "line_items[tax1_name][1] : line_items_taxes_tax_name[1]"
    - "line_items[amount][2] : line_items_amount[2]"
    - "line_items[amount][3] : line_items_amount[3]"
    - "line_items[amount][4] : line_items_amount[4]"
    - "line_items[amount][5] : line_items_amount[5]"
    - "line_items[amount][6] : line_items_amount[6]"
    - "line_items[date_from][2] : line_items_date_from[2]"
    - "line_items[date_from][3] : line_items_date_from[3]"
    - "line_items[date_from][4] : line_items_date_from[4]"
    - "line_items[date_from][5] : line_items_date_from[5]"
    - "line_items[date_from][6] : line_items_date_from[6]"
    - "line_items[date_to][2] : line_items_date_to[2]"
    - "line_items[date_to][3] : line_items_date_to[3]"
    - "line_items[date_to][4] : line_items_date_to[4]"
    - "line_items[date_to][5] : line_items_date_to[5]"
    - "line_items[date_to][6] : line_items_date_to[6]"
    - "line_items[description][2] : line_items_description[2]"
    - "line_items[description][3] : line_items_description[3]"
    - "line_items[description][4] : line_items_description[4]"
    - "line_items[description][5] : line_items_description[5]"
    - "line_items[description][6] : line_items_description[6]"
    - "line_items[entity_id][2] : line_items_entity_id[2]"
    - "line_items[entity_id][3] : line_items_entity_id[3]"
    - "line_items[entity_id][4] : line_items_entity_id[4]"
    - "line_items[entity_id][5] : line_items_entity_id[5]"
    - "line_items[entity_id][6] : line_items_entity_id[6]"
    - "line_items[entity_type][2] : line_items_entity_type[2]"
    - "line_items[entity_type][3] : line_items_entity_type[3]"
    - "line_items[entity_type][4] : line_items_entity_type[4]"
    - "line_items[entity_type][5] : line_items_entity_type[5]"
    - "line_items[entity_type][6] : line_items_entity_type[6]"
    - "line_items[id][2] : line_items_id[2]"
    - "line_items[id][3] : line_items_id[3]"
    - "line_items[id][4] : line_items_id[4]"
    - "line_items[id][5] : line_items_id[5]"
    - "line_items[id][6] : line_items_id[6]"
    - "line_items[quantity][2] : line_items_quantity[2]"
    - "line_items[quantity][3] : line_items_quantity[3]"
    - "line_items[quantity][4] : line_items_quantity[4]"
    - "line_items[quantity][5] : line_items_quantity[5]"
    - "line_items[quantity][6] : line_items_quantity[6]"

  String_Columns:
    - "line_items[id] : Line_Item_Id"
    - "invoice[id] : Invoice_Number"

  Date_Columns:
    - "line_items[date_from][0] : line_items_date_from[0]"
    - "line_items[date_to][0] : line_items_date_to[0]"
    - "line_items[date_from][2] : line_items_date_from[2]"
    - "line_items[date_from][3] : line_items_date_from[3]"
    - "line_items[date_from][4] : line_items_date_from[4]"
    - "line_items[date_from][5] : line_items_date_from[5]"
    - "line_items[date_from][6] : line_items_date_from[6]"
    - "line_items[date_to][2] : line_items_date_to[2]"
    - "line_items[date_to][3] : line_items_date_to[3]"
    - "line_items[date_to][4] : line_items_date_to[4]"
    - "line_items[date_to][5] : line_items_date_to[5]"
    - "line_items[date_to][6] : line_items_date_to[6]"
    - "subscription[start_date] : subscription_start_date"
    - "invoice[date] : invoice[date]"
    - "line_items[date_from][0] : line_items[date_from][0]"
    - "line_items[date_to][0] : line_items[date_to][0]"
    - "payments[date][0] : payments[date][0]"
    - "line_items[date_from][1] : line_items[date_from][1]"
    - "line_items[date_to][1] : line_items[date_to][1]"
    - "line_items[date_from][2] : line_items[date_from][2]"
    - "line_items[date_to][2] : line_items[date_to][2]"
    - "line_items[date_from][3] : line_items[date_from][3]"
    - "line_items[date_from][4] : line_items[date_from][4]"
    - "line_items[date_to][3] : line_items[date_to][3]"
    - "line_items[date_to][4] : line_items[date_to][4]"
    - "line_items[date_from] : Date_From"
    - "line_items[date_to] : Date_To"
    - "customer[created_at] : customer_created_at"
    - "invoice[date] : invoice_date"
    - "payments[date][0] : payments_txn_date[0]"
    - "line_items[date_from][0] : line_item_date_from[0]"
    - "line_items[date_to][0] : line_item_date_to[0]"
    - "line_items[date_from][1] : line_item_date_from[1]"
    - "line_items[date_to][1] : line_item_date_to[1]"
    - "line_items[date_from][2] : line_item_date_from[2]"
    - "line_items[date_to][2] : line_item_date_to[2]"
    - "line_items[date_from][3] : line_item_date_from[3]"
    - "line_items[date_to][3] : line_item_date_to[3]"
    - "line_items[date_from][4] : line_item_date_from[4]"
    - "line_items[date_to][4] : line_item_date_to[4]"
    - "line_items[date_from][5] : line_item_date_from[5]"
    - "line_items[date_to][5] : line_item_date_to[5]"
    - "line_items[date_from][6] : line_item_date_from[6]"
    - "line_items[date_to][6] : line_item_date_to[6]"
    - "line_items[date_from][7] : line_item_date_from[7]"
    - "line_items[date_to][7] : line_item_date_to[7]"
    - "line_items[date_from][8] : line_item_date_from[8]"
    - "line_items[date_to][8] : line_item_date_to[8]"
    - "line_items[date_from][9] : line_item_date_from[9]"
    - "line_items[date_to][9] : line_item_date_to[9]"
    - "subscription[created_at] : subscription_created_at"
    - "subscription[started_at] : subscription_started_at"
    - "subscription[current_term_start] : subscription_current_term_start"
    - "subscription[current_term_end] : subscription_current_term_end"
    - "invoice[date] : invoice_date"
    - "invoice[due_date] : invoice_due_date"
    - "line_items[date_from][0] : line_item_date_from[0]"
    - "line_items[date_to][0] : line_item_date_to[0]"
    - "line_items[date_from][1] : line_item_date_from[1]"
    - "line_items[date_to][1] : line_item_date_to[1]"
    - "line_items[date_from][2] : line_item_date_from[2]"
    - "line_items[date_to][2] : line_item_date_to[2]"
    - "line_items[date_from][3] : line_item_date_from[3]"
    - "line_items[date_to][3] : line_item_date_to[3]"
    - "payments[date][0] : payments_txn_date[0]"
    - "subscription[created_at] : subscription_created_at"
    - "subscription[started_at] : subscription_started_at"
    - "invoice[due_date] : invoice_due_date"
    - "subscription[created_at] : subscription_created_at"
    - "subscription[trial_start] : subscription_trial_start"
    - "subscription[trial_end] : subscription_trial_end"
    - "subscription[started_at] : subscription_started_at"
    - "subscription[current_term_start] : subscription_current_term_start"
    - "subscription[current_term_end] : subscription_current_term_end"
    - "subscription[cancelled_at] : subscription_cancelled_at"
    - "subscription[start_date] : subscription_started_at"
    - "subscription[current_term_start] : subscription_current_term_start"
    - "subscription[current_term_end] : subscription_current_term_end"
    - "subscription[pause_date] : subscription_pause_date"
    - "invoice[date] : Invoice_Date"
    - "payments[date][0] : Paid_On"
    - "subscription[created_at] : subscriptions.created_at"
    - "subscription[started_at] : subscriptions.started_at"
    - "subscription[current_term_start] : subscriptions.current_term_start"
    - "subscription[current_term_end] : subscriptions.current_term_end"
    - "subscription[cancelled_at] : subscriptions.cancelled_at"
    - "customer[created_at] : Created_At"
    - "invoice[date] : date"
    - "line_items[date_from][0] : line_items[date_from][0]"
    - "line_items[date_to][0] : line_items[date_to][0]"
    - "payments[date][0] : payments_0_date"
    - "subscription[created_at] : subscription_created_at"
    - "customer[created_at] : customer_created_at"
    - "subscription[started_at] : subscription_started_at"
    - "subscription[current_term_start] : subscription_current_term_start"
    - "subscription[current_term_end] : subscription_current_term_end"
    - "subscription[cancelled_at] : subscription_cancelled_at"
    - "customer[created_at] : customer_created_at"
    - 'created : invoice[date]'
    - 'lines.data[0].period.start : line_items[date_from][0]'
    - 'lines.data[0].period.end : line_items[date_to][0]'
    - 'lines.data[1].period.start : line_items[date_from][1]'
    - 'lines.data[1].period.end : line_items[date_to][1]'
    - 'lines.data[2].period.start : line_items[date_from][2]'
    - 'lines.data[2].period.end : line_items[date_to][2]'
    - 'lines.data[3].period.start : line_items[date_from][3]'
    - 'lines.data[3].period.end : line_items[date_to][3]'

  Int_Columns:
    - "customer[phone] : customer_phone"
    - "billing_address[phone] : customer_billing_address_phone"
    - "payments[amount][0] : payments_txn_amount[0]"
    - "line_items[unit_amount][0] : line_item_unit_amount[0]"
    - "line_items[quantity][1] : line_item_quantity[1]"
    - "line_items[amount][1] : line_item_amount[1]"
    - "line_items[quantity][2] : line_item_quantity[2]"
    - "line_items[amount][2] : line_item_amount[2]"
    - "line_items[quantity][3] : line_item_quantity[3]"
    - "line_items[amount][3] : line_item_amount[3]"
    - "line_items[quantity][4] : line_item_quantity[4]"
    - "line_items[amount][4] : line_item_amount[4]"
    - "line_items[quantity][5] : line_item_quantity[5]"
    - "line_items[amount][5] : line_item_amount[5]"
    - "line_items[quantity][6] : line_item_quantity[6]"
    - "line_items[amount][6] : line_item_amount[6]"
    - "line_items[quantity][7] : line_item_quantity[7]"
    - "line_items[amount][7] : line_item_amount[7]"
    - "line_items[quantity][8] : line_item_quantity[8]"
    - "line_items[amount][8] : line_item_amount[8]"
    - "line_items[quantity][9] : line_item_quantity[9]"
    - "line_items[amount][9] : line_item_amount[9]"
    - "subscription_items[quantity][1] : item_quantity[1]"
    - "subscription_items[unit_price][1] : item_unit_price[1]"
    - "subscription_items[quantity][2] : item_quantity[2]"
    - "subscription_items[unit_price][2] : item_unit_price[2]"
    - "subscription_items[quantity][3] : item_quantity[3]"
    - "subscription_items[unit_price][3] : item_unit_price[3]"
    - "subscription_items[quantity][4] : item_quantity[4]"
    - "subscription_items[unit_price][4] : item_unit_price[4]"
    - "subscription_items[quantity][5] : item_quantity[5]"
    - "subscription_items[unit_price][5] : item_unit_price[5]"
    - "subscription_items[quantity][6] : item_quantity[6]"
    - "subscription_items[unit_price][6] : item_unit_price[6]"
    - "subscription_items[quantity][7] : item_quantity[7]"
    - "subscription_items[unit_price][7] : item_unit_price[7]"
    - "subscription_items[quantity][8] : item_quantity[8]"
    - "subscription_items[unit_price][8] : item_unit_price[8]"
    - "subscription_items[quantity][9] : item_quantity[9]"
    - "subscription_items[unit_price][9] : item_unit_price[9]"
    - "subscription_items[quantity][0] : item_quantity[0]"
    - "subscription_items[unit_price][0] : item_unit_price[0]"
    - "subscription_items[quantity][1] : item_quantity[1]"
    - "subscription_items[unit_price][1] : item_unit_price[1]"
    - "subscription_items[quantity][2] : item_quantity[2]"
    - "subscription_items[unit_price][2] : item_unit_price[2]"
    - "subscription_items[quantity][3] : item_quantity[3]"
    - "subscription_items[unit_price][3] : item_unit_price[3]"
    - "shipping_address[zip] : subscription_shipping_address_zip"
    - "subscription[po_number] : subscription_po_number"
    - "invoice[total] : invoice_total"
    - "line_items[quantity][0] : line_item_quantity[0]"
    - "line_items[unit_amount][0] : line_item_unit_amount[0]"
    - "line_items[tax1_amount][0] : line_item_taxes_tax_amount[0]"
    - "line_items[quantity][1] : line_item_quantity[1]"
    - "line_items[unit_amount][1] : line_item_unit_amount[1]"
    - "line_items[tax1_amount][1] : line_item_taxes_tax_amount[1]"
    - "line_items[quantity][2] : line_item_quantity[2]"
    - "line_items[unit_amount][2] : line_item_unit_amount[2]"
    - "line_items[tax1_amount][2] : line_item_taxes_tax_name[2]"
    - "line_items[quantity][3] : line_item_quantity[3]"
    - "line_items[unit_amount][3] : line_item_unit_amount[3]"
    - "line_items[tax1_amount][3] : line_item_tax1_amount[3]"
    - "payments[amount][0] : payments_txn_amount[0]"
    - "subscription_items[quantity][0] : item_quantity[0]"
    - "subscription_items[quantity][1] : item_quantity[1]"
    - "subscription_items[quantity][2] : item_quantity[2]"
    - "subscription_items[quantity][3] : item_quantity[3]"
    - "subscription_items[quantity][4] : item_quantity[4]"
    - "subscription_items[quantity][5] : item_quantity[5]"

  Float_Columns:
    - "subscription_items[unit_price][0] : item_unit_price[0]"
    - "subscription_items[unit_price][1] : item_unit_price[1]"
    - "subscription_items[unit_price][2] : item_unit_price[2]"
    - "subscription_items[unit_price][3] : item_unit_price[3]"
    - "subscription_items[unit_price][4] : item_unit_price[4]"
    - "subscription_items[unit_price][5] : item_unit_price[5]"

  Email_Columns:
    - "customer[email] : Email"
    - "customer[email] : customer_email"
    - "billing_address[email] : customer_billing_address_email"

  Zip_Columns:
    - "billing_address[zip] : customer_billing_address_zip"
    - "billing_address[zip] : Billing_Address_Zip"
    - "shipping_address[zip] : subscription_shipping_address_zip"
    - "billing_address[zip] : customer_billing_address_zip"
    - 'customer_shipping.address.postal_code : shipping_address[state_code]'
    - 'address.postal_code : billing_address[zip]'






